# Site settings
title:       Game162
description: "Hey batter batter, hey batter batter, swing!"
baseurl:     ""
gems:
  - jekyll-sitemap

defaults:
  -
    values:
      layout: "fact-single"

future:    false
permalink: /:title/

paginate: 10
paginate_path: "/archive/page/:num"

my_setting: "hihi"